name: tst
summary: Test python snap
base: core18
adopt-info: tst

grade: devel
confinement: classic

apps:
  unwrapped:
    command: bin/tst
  wrapped:
    command: bin/snap-env $SNAP/bin/tst
  tst:  # default command (same name as snap)
    command: bin/snap-env $SNAP/bin/tst

parts:
  tst:
    plugin: python
    python-version: python3
    source: .
    parse-info: ['setup.py']
    requirements:
      - requirements.txt
    override-build: |
      snapcraftctl build
      cp helpers/snap-env $SNAPCRAFT_PART_INSTALL/bin
